# Generated by Django 5.2.17 on 2026-09-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='e.g. "otp_login", "order_paid", "order_shipped"', unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True, help_text='Use {placeholders} like {code}, {orderNumber}')),
                ('is_active', models.BooleanField(default=True)),
                ('kavenegar_template_name', models.CharField(blank=True, help_text='نام الگوی Lookup در پنل کاوه\u200cنگار (نه شناسه عددی). خالی = ارسال متن معمولی با body.', max_length=100)),
                ('kavenegar_token_field', models.CharField(blank=True, help_text='کدام کلید از context به\u200cعنوان %token% به کاوه\u200cنگار فرستاده شود، مثلاً code یا orderNumber.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('body', models.TextField(blank=True)),
                ('kavenegar_template_name', models.CharField(blank=True, max_length=100)),
                ('kavenegar_token', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('queued', 'در صف'), ('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق')], default='queued', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.smstemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'created_at'], name='notificatio_phone_48a3b1_idx')],
            },
        ),
    ]
