# Generated by Django 5.2.17 on 2026-09-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_seed_order_sms_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='kavenegar_token',
        ),
        migrations.RemoveField(
            model_name='smstemplate',
            name='kavenegar_token_field',
        ),
        migrations.AddField(
            model_name='smslog',
            name='kavenegar_tokens',
            field=models.JSONField(blank=True, default=dict, help_text='مقادیر پاک\u200cسازی\u200cشده\u200cی token/token2/... در لحظه\u200cی ارسال.'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='kavenegar_token_map',
            field=models.JSONField(blank=True, default=dict, help_text='نگاشت پارامتر کاوه\u200cنگار به کلید context، مثلاً {"token": "orderNumber", "token10": "firstName"}.'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='key',
            field=models.SlugField(help_text='e.g. "otp_login", "order_confirmed", "order_shipped"', unique=True),
        ),
    ]
