# Generated by Django 5.2.17 on 2026-09-24 13:05

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('kavenegar', 'کاوه\u200cنگار'), ('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی'), ('snapppay', 'اسنپ\u200cپی'), ('digipay', 'دیجی\u200cپی')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('credentials', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='JSON string, e.g. {"apiKey": "...", "merchantId": "..."}')),
                ('is_active', models.BooleanField(default=True, help_text='controls checkout-time visibility')),
                ('is_sandbox', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/gateways/')),
                ('description', models.CharField(blank=True, help_text='مثلاً «پرداخت اعتباری» برای اسنپ\u200cپی', max_length=150)),
            ],
            options={
                'ordering': ['service', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField()),
                ('free_above', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_days', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'cost'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('economic_code', models.CharField(blank=True, help_text='کد اقتصادی', max_length=30)),
                ('national_id', models.CharField(blank=True, help_text='شناسه ملی', max_length=30)),
                ('phone_display', models.CharField(blank=True, max_length=30)),
                ('phone_href', models.CharField(blank=True, help_text='e.g. "+982112345678" for tel:', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('business_hours', models.JSONField(default=list, help_text='[{day, time}, ...]')),
                ('instagram_url', models.URLField(blank=True, help_text='لینک کامل، مثلاً https://instagram.com/arbyte — خالی بگذار تا در فوتر/تماس با ما نمایش داده نشود.')),
                ('telegram_url', models.URLField(blank=True, help_text='لینک کامل — خالی بگذار تا نمایش داده نشود.')),
                ('whatsapp_url', models.URLField(blank=True, help_text='لینک کامل (مثلاً https://wa.me/98912...) — خالی بگذار تا نمایش داده نشود.')),
                ('linkedin_url', models.URLField(blank=True, help_text='لینک کامل — خالی بگذار تا نمایش داده نشود.')),
                ('youtube_url', models.URLField(blank=True, help_text='لینک کامل — خالی بگذار تا نمایش داده نشود.')),
                ('pinterest_url', models.URLField(blank=True, help_text='لینک کامل — خالی بگذار تا نمایش داده نشود.')),
                ('google_maps_embed', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('trust_badge_label', models.CharField(blank=True, max_length=100)),
                ('trust_badge_image', models.ImageField(blank=True, help_text='فقط اگر نماد اعتمادت eNamad نیست و عکس ثابت داری از اینجا آپلود کن. فرمت PNG (پس\u200cزمینه شفاف) یا SVG، حداقل ۱۲۰×۱۲۰ پیکسل، حجم زیر ۲۰۰ کیلوبایت. برای eNamad به\u200cجایش «تصویر نماد (لینک eNamad)» را پر کن.', null=True, upload_to='settings/')),
                ('trust_badge_image_url', models.URLField(blank=True, help_text='برای eNamad: کل کد نماد را در فیلد «لینک نماد» پیست کن، این فیلد خودکار پر می\u200cشود.', max_length=500)),
                ('trust_badge_url', models.URLField(blank=True, help_text='لینک نماد. برای eNamad می\u200cتوانی کل کد <a>...</a> نماد را همینجا پیست کنی -- لینک و عکس هردو خودکار استخراج می\u200cشوند.', max_length=500)),
                ('payment_gateway_label', models.CharField(blank=True, max_length=100)),
                ('payment_gateway_image', models.ImageField(blank=True, help_text='لوگوی درگاه پرداخت که در فوتر کنار «نماد اعتماد» نشان داده می\u200cشود. فرمت PNG (پس\u200cزمینه شفاف) یا SVG، حداقل ۱۲۰×۱۲۰ پیکسل، حجم زیر ۲۰۰ کیلوبایت.', null=True, upload_to='settings/')),
                ('logo_light', models.ImageField(blank=True, help_text='فعلاً در سایت زنده استفاده نمی\u200cشود — سایت از یک لوگوی طراحی\u200cشده ثابت استفاده می\u200cکند، نه از این آپلود.', null=True, upload_to='settings/')),
                ('logo_dark', models.ImageField(blank=True, help_text='فعلاً در سایت زنده استفاده نمی\u200cشود.', null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, help_text='فعلاً در سایت زنده استفاده نمی\u200cشود — فاوآیکون فعلی از فایل ثابت index.html خوانده می\u200cشود. فرمت ICO یا PNG ۳۲×۳۲ یا ۶۴×۶۴ پیکسل.', null=True, upload_to='settings/')),
                ('default_og_image', models.ImageField(blank=True, help_text='فعلاً در سایت زنده استفاده نمی\u200cشود — تصویر پیش\u200cفرض اشتراک\u200cگذاری از فایل ثابت خوانده می\u200cشود. فرمت JPG یا PNG، ۱۲۰۰×۶۳۰ پیکسل.', null=True, upload_to='settings/')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50)),
                ('owner_notification_phone', models.CharField(blank=True, help_text='یک یا چند شماره، جدا با کاما — مثلاً 09120000000,09121111111', max_length=200)),
                ('notify_owner_new_order', models.BooleanField(default=True, help_text='پیامک به کارفرما پس از پرداخت موفق هر سفارش (نه هنگام ثبت سفارش pending)')),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
