# Generated by Django 5.2.17 on 2026-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='card_to_card_holder_name',
            field=models.CharField(blank=True, help_text='نام صاحب حساب', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='card_to_card_number',
            field=models.CharField(blank=True, help_text='شماره کارت، بدون خط\u200cتیره', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='card_to_card_sheba',
            field=models.CharField(blank=True, help_text='شماره شبا، با IR', max_length=30),
        ),
        migrations.AlterField(
            model_name='apicredential',
            name='service',
            field=models.CharField(choices=[('kavenegar', 'کاوه\u200cنگار'), ('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی'), ('snapppay', 'اسنپ\u200cپی'), ('digipay', 'دیجی\u200cپی'), ('balepay', 'بله\u200cپی')], max_length=20),
        ),
    ]
