# Generated by Django 5.2.17 on 2026-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_seed_dev_shipping_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='postal_code',
            field=models.CharField(blank=True, help_text='کد پستی ۱۰ رقمی برای فاکتور/کارت گارانتی', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='test_period_days',
            field=models.PositiveIntegerField(default=7, help_text='storeFacts.policies.returnDays پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warranty_terms',
            field=models.TextField(blank=True, help_text='متن شرایط گارانتی؛ خالی = بخش شرایط در کارت پنهان می\u200cشود'),
        ),
    ]
