# Generated by Django 5.2.17 on 2026-09-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_sitesettings_postal_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="card_to_card_active",
            field=models.BooleanField(
                default=True,
                help_text="روش کارت\u200cبه\u200cکارت در چک\u200cاوت فعال باشد",
            ),
        ),
    ]
