# Generated by Django 5.2.17 on 2026-10-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0005_f01_card_to_card_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicredential",
            name="service",
            field=models.CharField(
                choices=[
                    ("kavenegar", "کاوه\u200cنگار"),
                    ("zarinpal", "زرین\u200cپال"),
                    ("idpay", "آیدی\u200cپی"),
                    ("snapppay", "اسنپ\u200cپی"),
                    ("digipay", "دیجی\u200cپی"),
                    ("balepay", "بله\u200cپی"),
                    ("torob", "ترب"),
                ],
                max_length=20,
            ),
        ),
    ]
