# Generated by Django 5.2.17 on 2026-10-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0006_alter_apicredential_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="balepay_bot_username",
            field=models.CharField(
                blank=True, help_text="بدون @، مثلاً arbytebot", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="online_payment_limit_rial",
            field=models.PositiveBigIntegerField(
                default=150000000,
                help_text="سقف هر پرداخت آنلاین (ریال)؛ پیش\u200cفرض ۱۵ میلیون تومان",
            ),
        ),
    ]
