# Generated by Django 5.2.17 on 2026-09-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_sitesettings_payment_gateway_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='لینک کامل، مثلاً https://instagram.com/arbyte — خالی بگذار تا در فوتر/تماس با ما نمایش داده نشود.'),
        ),
    ]
