# Generated by Django 5.2.17 on 2026-09-24 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.content.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('محصول', 'محصول'), ('طراحی', 'طراحی'), ('آموزش', 'آموزش'), ('سبک زندگی', 'سبک زندگی'), ('جامعه', 'جامعه')], max_length=20)),
                ('sections', models.JSONField(default=list, help_text='[{id, heading, body}, ...] — matches frontend BlogSection[]')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('external_cover_url', models.CharField(blank=True, help_text='Static asset path, used until a real image is uploaded.', max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('author_role', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('reading_time', models.PositiveIntegerField(default=1, help_text='minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=apps.content.models.generate_tracking_code, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('newsletter', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HERO', 'هیرو'), ('CATEGORY_GRID', 'شبکه دسته\u200cبندی\u200cها'), ('FLAGSHIP_DUEL', 'دوئل پرچم\u200cدار'), ('PRODUCT_RAIL', 'ردیف محصولات'), ('CAMPAIGN', 'کمپین'), ('BENEFITS', 'مزایا'), ('BLOG_RAIL', 'ردیف مجله')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('cta_label', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_url', models.CharField(blank=True, max_length=300, null=True)),
                ('image_desktop', models.CharField(blank=True, max_length=500, null=True)),
                ('image_mobile', models.CharField(blank=True, max_length=500, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده')], default='pending', max_length=10)),
                ('admin_reply', models.TextField(blank=True)),
                ('verified_purchase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=10)),
                ('value', models.PositiveIntegerField(help_text='percent (1-100) or Toman amount, per `type`')),
                ('min_order_value', models.PositiveIntegerField(default=0)),
                ('max_discount', models.PositiveIntegerField(blank=True, help_text='cap for percent coupons', null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
