# Generated by Django 5.2.17 on 2026-09-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='price_at_save',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
