# Generated by Django 5.2.17 on 2026-09-28 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_favorite_price_at_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_order_value',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='products',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='starts_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used_count',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='value',
        ),
        migrations.AddField(
            model_name='coupon',
            name='amount_toman',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='maximum_discount_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_order_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='percent_basis_points',
            field=models.PositiveIntegerField(blank=True, help_text='۱۰۰۰۰ = ۱۰۰٪', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('PERCENT', 'درصدی'), ('AMOUNT', 'مبلغ ثابت')], max_length=10),
        ),
    ]
