# Generated by Django 5.2.17 on 2026-09-29 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_requires_serial_product_warranty_months_and_more"),
        ("content", "0005_seed_dev_coupon"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeoMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=320, null=True),
                ),
                ("canonical", models.CharField(blank=True, max_length=500, null=True)),
                ("robots", models.CharField(blank=True, max_length=100, null=True)),
                ("og_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "og_description",
                    models.CharField(blank=True, max_length=320, null=True),
                ),
                ("og_image", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "brand",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo",
                        to="catalog.category",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
