# Generated by Django 5.2.17 on 2026-09-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_f03_pricing_import_campaign"),
        ("content", "0006_f02_seo_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("rules", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "-start_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="content.campaign",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_targets",
                        to="catalog.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_targets",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["campaign"], name="content_cam_campaig_4192c6_idx"
                    ),
                    models.Index(
                        fields=["product"], name="content_cam_product_112f43_idx"
                    ),
                    models.Index(
                        fields=["category"], name="content_cam_categor_ea5b86_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("category__isnull", True), ("product__isnull", False)
                            ),
                            models.Q(
                                ("category__isnull", False), ("product__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="campaign_target_exactly_one",
                    )
                ],
            },
        ),
    ]
