# Generated by Django 5.2.17 on 2026-09-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_seed_hero_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogspread',
            name='catalog',
        ),
        migrations.DeleteModel(
            name='CatalogEdition',
        ),
        migrations.DeleteModel(
            name='CatalogFile',
        ),
        migrations.DeleteModel(
            name='CatalogSpread',
        ),
    ]
