# Generated by Django 5.2.17 on 2026-09-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_f03_pricing_import_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover_alt",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
