# Generated by Django 5.2.17 on 2026-09-29 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_f03_pricing_import_campaign"),
        ("content", "0008_f04_blog_cover_alt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=200)),
                ("hero_body", models.TextField(blank=True)),
                ("story_title", models.CharField(blank=True, max_length=200)),
                (
                    "story_body",
                    models.TextField(
                        blank=True,
                        help_text="پاراگراف\u200cها با یک خط خالی جدا می\u200cشوند",
                    ),
                ),
                ("principles_title", models.CharField(blank=True, max_length=200)),
                ("principles", models.JSONField(blank=True, default=list)),
                ("timeline_title", models.CharField(blank=True, max_length=200)),
                ("timeline", models.JSONField(blank=True, default=list)),
                ("team_title", models.CharField(blank=True, max_length=200)),
                ("team", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("terms", "شرایط استفاده"),
                            ("privacy", "حریم خصوصی"),
                            ("shipping", "ارسال"),
                            ("returns", "مرجوعی"),
                            ("warranty", "گارانتی"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                ("body", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="order_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("راهنمای خرید", "راهنمای خرید"),
                    ("بررسی", "بررسی"),
                    ("مقایسه", "مقایسه"),
                    ("نگهداری", "نگهداری"),
                    ("گیمینگ", "گیمینگ"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.UniqueConstraint(
                fields=("product", "user"), name="review_one_per_user_product"
            ),
        ),
    ]
