# Generated by Django 5.2.17 on 2026-09-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_g01_content_pages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_path", models.CharField(max_length=500, unique=True)),
                ("to_path", models.CharField(max_length=500)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        choices=[(301, "دائمی (301)"), (302, "موقت (302)")], default=301
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_auto",
                    models.BooleanField(
                        default=False,
                        help_text="ساخته\u200cشده خودکار با تغییر slug/حذف",
                    ),
                ),
                ("hits", models.PositiveIntegerField(default=0)),
                ("last_hit_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
