# Generated by Django 5.2.17 on 2026-09-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConsoleIndexStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexed_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('issues', models.JSONField(default=list, help_text='[{page, reason}, ...]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchConsolePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page', models.CharField(max_length=500)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('position', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date', '-clicks'],
            },
        ),
        migrations.CreateModel(
            name='SearchConsolePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('avg_position', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SearchConsoleQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('query', models.CharField(max_length=255)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('position', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date', '-clicks'],
            },
        ),
        migrations.CreateModel(
            name='SearchConsoleSitemapStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_urls', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role', to='auth.group')),
            ],
            options={
                'ordering': ['group__name'],
                'permissions': [('sec_homepage_view', 'صفحه اصلی — view'), ('sec_homepage_create', 'صفحه اصلی — create'), ('sec_homepage_edit', 'صفحه اصلی — edit'), ('sec_homepage_delete', 'صفحه اصلی — delete'), ('sec_products_view', 'محصولات — view'), ('sec_products_create', 'محصولات — create'), ('sec_products_edit', 'محصولات — edit'), ('sec_products_delete', 'محصولات — delete'), ('sec_categories_view', 'دسته\u200cبندی\u200cها — view'), ('sec_categories_create', 'دسته\u200cبندی\u200cها — create'), ('sec_categories_edit', 'دسته\u200cبندی\u200cها — edit'), ('sec_categories_delete', 'دسته\u200cبندی\u200cها — delete'), ('sec_specs_view', 'مشخصات محصولات — view'), ('sec_specs_create', 'مشخصات محصولات — create'), ('sec_specs_edit', 'مشخصات محصولات — edit'), ('sec_specs_delete', 'مشخصات محصولات — delete'), ('sec_pricing_view', 'اصلاح قیمت — view'), ('sec_pricing_edit', 'اصلاح قیمت — edit'), ('sec_cost_price_view', 'قیمت تمام\u200cشده محصول — view'), ('sec_orders_view', 'سفارشات — view'), ('sec_orders_edit', 'سفارشات — edit'), ('sec_inventory_view', 'موجودی — view'), ('sec_inventory_edit', 'موجودی — edit'), ('sec_stock_ledger_view', 'کاردکس — view'), ('sec_stock_ledger_create', 'کاردکس — create'), ('sec_returns_view', 'مرجوعی\u200cها — view'), ('sec_returns_edit', 'مرجوعی\u200cها — edit'), ('sec_messages_view', 'پیام\u200cها — view'), ('sec_messages_edit', 'پیام\u200cها — edit'), ('sec_reviews_view', 'نظرات — view'), ('sec_reviews_edit', 'نظرات — edit'), ('sec_blog_view', 'بلاگ — view'), ('sec_blog_create', 'بلاگ — create'), ('sec_blog_edit', 'بلاگ — edit'), ('sec_blog_delete', 'بلاگ — delete'), ('sec_coupons_view', 'کدهای تخفیف — view'), ('sec_coupons_create', 'کدهای تخفیف — create'), ('sec_coupons_edit', 'کدهای تخفیف — edit'), ('sec_coupons_delete', 'کدهای تخفیف — delete'), ('sec_reports_view', 'گزارش\u200cهای فروش و سود — view'), ('sec_settings_view', 'تنظیمات سایت — view'), ('sec_settings_edit', 'تنظیمات سایت — edit'), ('sec_credentials_view', 'کلیدهای API — view'), ('sec_credentials_create', 'کلیدهای API — create'), ('sec_credentials_edit', 'کلیدهای API — edit'), ('sec_credentials_delete', 'کلیدهای API — delete'), ('sec_users_view', 'کاربران — view'), ('sec_users_create', 'کاربران — create'), ('sec_users_edit', 'کاربران — edit'), ('sec_roles_view', 'مدیریت نقش\u200cها و دسترسی — view'), ('sec_roles_edit', 'مدیریت نقش\u200cها و دسترسی — edit'), ('sec_activity_log_view', 'لاگ فعالیت — view'), ('sec_search_console_view', 'سرچ کنسول — view')],
            },
        ),
    ]
