# Generated by Django 5.2.17 on 2026-09-24 13:05

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STOCK_IN', 'ورود به انبار'), ('STOCK_OUT', 'خروج از انبار'), ('ADJUSTMENT', 'اصلاح موجودی'), ('RESERVATION', 'رزرو'), ('RELEASE', 'آزادسازی رزرو')], max_length=12)),
                ('quantity_change', models.IntegerField(help_text='Signed.')),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('reference', models.CharField(blank=True, help_text='e.g. order number', max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventory', serialize=False, to='catalog.productvariant')),
                ('quantity', models.IntegerField(default=0)),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('available_quantity', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '-', models.F('reserved_quantity')), output_field=models.IntegerField())),
                ('low_stock_threshold', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'inventory',
                'constraints': [models.CheckConstraint(condition=models.Q(('available_quantity__gte', 0)), name='inventory_available_quantity_non_negative')],
            },
        ),
    ]
