# Generated by Django 5.2.17 on 2026-09-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_price', models.BigIntegerField()),
                ('new_price', models.BigIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'price histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gtin', models.CharField(blank=True, max_length=50, null=True)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=160, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'آکبند'), ('OPEN_BOX', 'اپن\u200cباکس'), ('STOCK', 'استوک'), ('LIKE_NEW', 'درحدنو')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال')], default='ACTIVE', max_length=10)),
                ('is_visible_on_site', models.BooleanField(default=True)),
                ('is_visible_in_search', models.BooleanField(default=True)),
                ('is_visible_in_category', models.BooleanField(default=True)),
                ('return_policy_note', models.TextField(blank=True, null=True)),
                ('shipping_note', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_value', models.CharField(blank=True, max_length=150, null=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('price_model', models.CharField(choices=[('FIXED', 'ثابت'), ('SUPPLIER_PLUS_PROFIT', 'قیمت تأمین\u200cکننده + سود')], default='FIXED', max_length=25)),
                ('supplier_price', models.BigIntegerField(blank=True, null=True)),
                ('profit_type', models.CharField(blank=True, choices=[('AMOUNT', 'مبلغ'), ('PERCENT', 'درصد')], max_length=10, null=True)),
                ('profit_amount_toman', models.BigIntegerField(blank=True, null=True)),
                ('profit_percent_basis_points', models.IntegerField(blank=True, null=True)),
                ('final_price', models.BigIntegerField()),
                ('compare_at_price', models.BigIntegerField(blank=True, null=True)),
                ('is_preorder', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name_fa', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('TEXT', 'متنی'), ('NUMBER', 'عددی'), ('BOOLEAN', 'بله/خیر'), ('SELECT', 'انتخابی'), ('MULTI_SELECT', 'چندانتخابی'), ('RANGE', 'بازه\u200cای'), ('COLOR', 'رنگ'), ('DATE', 'تاریخ')], max_length=15)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=False)),
                ('is_variant_axis', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name_fa'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('swatch_hex', models.CharField(blank=True, help_text='#RRGGBB', max_length=7, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField()),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='catalog_bra_slug_65677f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='brand_slug_unique_live')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image_main', models.CharField(blank=True, max_length=500, null=True)),
                ('image_banner', models.CharField(blank=True, max_length=500, null=True)),
                ('image_thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
