# Generated by Django 5.2.17 on 2026-09-24 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='specificationdefinition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specification_definitions', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='catalog.specificationdefinition'),
        ),
        migrations.AddField(
            model_name='specificationvalue',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.specificationdefinition'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_specifications', to='catalog.specificationvalue'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='catalog_cat_parent__5307be_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='category_slug_unique_live'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='catalog_pro_categor_7c1c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='catalog_pro_brand_i_69e6f6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='catalog_pro_status_521020_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='product_slug_unique_live'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='catalog_pro_product_f7f0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_187601_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='catalog_pro_product_460665_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('sku',), name='variant_sku_unique_live'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='variant_one_default_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('profit_amount_toman__isnull', True), ('profit_percent_basis_points__isnull', True)), models.Q(('profit_amount_toman__isnull', False), ('profit_percent_basis_points__isnull', True)), models.Q(('profit_amount_toman__isnull', True), ('profit_percent_basis_points__isnull', False)), _connector='OR'), name='variant_profit_value_shape'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['variant', 'created_at'], name='catalog_pri_variant_8e2c67_idx'),
        ),
        migrations.AddIndex(
            model_name='specificationdefinition',
            index=models.Index(fields=['category'], name='catalog_spe_categor_b8f60c_idx'),
        ),
        migrations.AddIndex(
            model_name='specificationvalue',
            index=models.Index(fields=['definition'], name='catalog_spe_definit_5f4919_idx'),
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(fields=['definition', 'numeric_value'], name='catalog_pro_definit_a5f042_idx'),
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(fields=['product'], name='catalog_pro_product_dde495_idx'),
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(fields=['variant'], name='catalog_pro_variant_47bcb7_idx'),
        ),
    ]
