# Generated by Django 5.2.17 on 2026-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_serial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, help_text='مدت گارانتی به ماه؛ خالی = بدون گارانتی جدا', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_provider',
            field=models.CharField(blank=True, help_text='مثلاً «گارانتی شرکتی»', max_length=150, null=True),
        ),
    ]
