# Generated by Django 5.2.17 on 2026-09-29 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_requires_serial_product_warranty_months_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="imports/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("headers", models.JSONField(default=list)),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("PROCESSING", "در حال اجرا"),
                            ("COMPLETED", "انجام\u200cشده"),
                            ("FAILED", "ناموفق"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_rows", models.IntegerField(default=0)),
                ("successful_rows", models.IntegerField(default=0)),
                ("failed_rows", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportJobRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "موفق"),
                            ("FAILED", "ناموفق"),
                            ("SKIPPED", "رد شده"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, help_text="create/update", max_length=10
                    ),
                ),
                ("sku_matched", models.CharField(blank=True, max_length=50, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="catalog.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
                "indexes": [
                    models.Index(
                        fields=["import_job"], name="catalog_imp_import__504dea_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profit_type",
                    models.CharField(
                        choices=[("AMOUNT", "مبلغ"), ("PERCENT", "درصد")], max_length=10
                    ),
                ),
                ("profit_amount_toman", models.BigIntegerField(blank=True, null=True)),
                (
                    "profit_percent_basis_points",
                    models.IntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_rules",
                        to="catalog.category",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_rules",
                        to="catalog.supplier",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["supplier"], name="catalog_pri_supplie_c8ec2b_idx"
                    ),
                    models.Index(
                        fields=["category"], name="catalog_pri_categor_921b56_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("profit_amount_toman__isnull", False),
                                ("profit_percent_basis_points__isnull", True),
                                ("profit_type", "AMOUNT"),
                            ),
                            models.Q(
                                ("profit_amount_toman__isnull", True),
                                ("profit_percent_basis_points__isnull", False),
                                ("profit_type", "PERCENT"),
                            ),
                            _connector="OR",
                        ),
                        name="price_rule_profit_matches_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.BigIntegerField()),
                ("is_available", models.BooleanField(default=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_products",
                        to="catalog.supplier",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_products",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["variant"], name="catalog_sup_variant_11fc45_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier", "variant"), name="supplier_product_unique"
                    )
                ],
            },
        ),
    ]
