# Generated by Django 5.2.17 on 2026-10-05 13:06

from django.db import migrations, models


def set_default_key_specs(apps, schema_editor):
    """AUDIT §۱۲.۴ — پردازنده/گرافیک/رم پیش‌فرض مشخصات کلیدی؛ ادمین بعداً تغییر می‌دهد."""
    from apps.catalog.key_specs import default_key_spec_order

    Definition = apps.get_model("catalog", "SpecificationDefinition")
    for definition in Definition.objects.filter(key_spec_order__isnull=True):
        order = default_key_spec_order(definition.key, definition.name_fa)
        if order is not None:
            definition.key_spec_order = order
            definition.save(update_fields=["key_spec_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_f03_pricing_import_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="specificationdefinition",
            name="key_spec_order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(set_default_key_specs, migrations.RunPython.noop),
    ]
