# Generated by Django 5.2.17 on 2026-10-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_key_spec_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A+', 'A+'), ('A++', 'A++'), ('A+++', 'A+++'), ('B', 'B'), ('B+', 'B+'), ('OPENBOX', 'OPENBOX'), ('KY.PEN.A', 'KY.PEN.A'), ('KY.PEN.A+', 'KY.PEN.A+'), ('BOX', 'BOX'), ('A++BOX', 'A++BOX')], max_length=20, null=True),
        ),
    ]
