# Generated by Django 5.2.17 on 2026-10-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_product_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_presale',
            field=models.BooleanField(default=False),
        ),
    ]
