# Generated by Django 5.2.17 on 2026-10-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_product_is_presale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='included_accessories',
            field=models.TextField(blank=True, null=True),
        ),
    ]
