from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from apps.torob import admin_views as torob_admin

from . import (
    account_admin,
    activity_log_views,
    auth,
    blog,
    campaigns,
    categories,
    contact_messages,
    content_pages,
    coupons,
    dashboard,
    homepage,
    imports,
    inventory,
    orders,
    payments,
    pricing,
    products,
    redirects,
    reports,
    returns,
    reviews,
    roles,
    search_console,
    settings_admin,
    specs,
    suppliers,
    uploads,
    users,
)

# F-02 — products/pricing/specs/inventory/homepage بازنویسی و دوباره وصل شدند
# (روی ProductVariant/Inventory/SpecificationDefinition/HomepageBlock).

urlpatterns = [
    # Auth
    path("admin/auth/login/", auth.AdminLoginView.as_view(), name="admin-login"),
    path("admin/auth/refresh/", TokenRefreshView.as_view(), name="admin-refresh"),
    path("admin/auth/change-password/", auth.AdminChangePasswordView.as_view(), name="admin-change-password"),
    path("admin/me/permissions/", roles.AdminMyPermissionsView.as_view(), name="admin-my-permissions"),
    # Roles & permissions (§7.5)
    path("admin/roles/", roles.AdminRoleListCreateView.as_view(), name="admin-role-list"),
    path("admin/roles/sections/", roles.AdminRoleSectionsView.as_view(), name="admin-role-sections"),
    path("admin/roles/<int:pk>/", roles.AdminRoleDetailView.as_view(), name="admin-role-detail"),
    # Dashboard
    path("admin/dashboard/", dashboard.AdminDashboardView.as_view(), name="admin-dashboard"),
    path("admin/dashboard/mark-seen/", dashboard.AdminDashboardMarkSeenView.as_view(), name="admin-dashboard-mark-seen"),
    # Categories
    path("admin/uploads/", uploads.AdminImageUploadView.as_view(), name="admin-upload"),
    path("admin/brands/", products.AdminBrandListCreateView.as_view(), name="admin-brand-list"),
    path("admin/brands/<int:pk>/", products.AdminBrandDetailView.as_view(), name="admin-brand-detail"),
    path("admin/products/", products.AdminProductListCreateView.as_view(), name="admin-product-list"),
    path("admin/products/<int:pk>/", products.AdminProductDetailView.as_view(), name="admin-product-detail"),
    path("admin/products/<int:pk>/images/", products.AdminProductImageListView.as_view(), name="admin-product-images"),
    path("admin/products/<int:pk>/images/reorder/", products.AdminProductImageReorderView.as_view(), name="admin-product-images-reorder"),
    path("admin/products/<int:pk>/images/<int:image_id>/", products.AdminProductImageDetailView.as_view(), name="admin-product-image-detail"),
    path("admin/products/<int:pk>/specs/", products.AdminProductSpecsView.as_view(), name="admin-product-specs"),
    path("admin/products/<int:pk>/variants/", products.AdminProductVariantsView.as_view(), name="admin-product-variants"),
    path("admin/products/<int:pk>/variants/preview/", products.AdminVariantPreviewView.as_view(), name="admin-product-variants-preview"),
    path("admin/specifications/", specs.AdminSpecDefinitionListCreateView.as_view(), name="admin-spec-list"),
    path("admin/specifications/<int:pk>/", specs.AdminSpecDefinitionDetailView.as_view(), name="admin-spec-detail"),
    path("admin/specifications/<int:definition_id>/values/", specs.AdminSpecValueListCreateView.as_view(), name="admin-spec-value-list"),
    path("admin/specifications/<int:definition_id>/values/<int:pk>/", specs.AdminSpecValueDetailView.as_view(), name="admin-spec-value-detail"),
    path("admin/inventory/", inventory.AdminInventoryListView.as_view(), name="admin-inventory-list"),
    path("admin/inventory/<int:variant_id>/", inventory.AdminInventoryThresholdView.as_view(), name="admin-inventory-threshold"),
    path("admin/inventory/stocktake.pdf", inventory.AdminStocktakePdfView.as_view(), name="admin-stocktake-pdf"),
    path("admin/inventory/transactions/", inventory.AdminInventoryTransactionListCreateView.as_view(), name="admin-inventory-transactions"),
    path("admin/pricing/", pricing.AdminPriceListView.as_view(), name="admin-price-list"),
    path("admin/pricing/price-list.pdf", pricing.AdminPriceListPdfView.as_view(), name="admin-price-list-pdf"),
    path("admin/pricing/preview/", pricing.AdminBulkPricePreviewView.as_view(), name="admin-price-preview"),
    path("admin/pricing/apply/", pricing.AdminBulkPriceApplyView.as_view(), name="admin-price-apply"),
    path("admin/pricing/<int:variant_id>/history/", pricing.AdminPriceHistoryView.as_view(), name="admin-price-history"),
    path("admin/suppliers/", suppliers.AdminSupplierListCreateView.as_view(), name="admin-supplier-list"),
    path("admin/suppliers/<int:pk>/", suppliers.AdminSupplierDetailView.as_view(), name="admin-supplier-detail"),
    path("admin/supplier-products/", suppliers.AdminSupplierProductListCreateView.as_view(), name="admin-supplier-product-list"),
    path("admin/supplier-products/<int:pk>/", suppliers.AdminSupplierProductDetailView.as_view(), name="admin-supplier-product-detail"),
    path("admin/price-rules/", suppliers.AdminPriceRuleListCreateView.as_view(), name="admin-price-rule-list"),
    path("admin/price-rules/<int:pk>/", suppliers.AdminPriceRuleDetailView.as_view(), name="admin-price-rule-detail"),
    path("admin/pricing/recalculate/", suppliers.AdminRecalculateView.as_view(), name="admin-price-recalculate"),
    path("admin/imports/", imports.AdminImportJobListCreateView.as_view(), name="admin-import-list"),
    path("admin/imports/template.xlsx", imports.AdminImportTemplateView.as_view(), name="admin-import-template"),
    path("admin/imports/<int:pk>/", imports.AdminImportJobDetailView.as_view(), name="admin-import-detail"),
    path("admin/imports/<int:pk>/preview/", imports.AdminImportPreviewView.as_view(), name="admin-import-preview"),
    path("admin/imports/<int:pk>/run/", imports.AdminImportRunView.as_view(), name="admin-import-run"),
    path("admin/imports/<int:pk>/errors.xlsx", imports.AdminImportErrorsXlsxView.as_view(), name="admin-import-errors"),
    path("admin/campaigns/", campaigns.AdminCampaignListCreateView.as_view(), name="admin-campaign-list"),
    path("admin/campaigns/<int:pk>/", campaigns.AdminCampaignDetailView.as_view(), name="admin-campaign-detail"),
    path("admin/campaigns/<int:pk>/preview/", campaigns.AdminCampaignPreviewView.as_view(), name="admin-campaign-preview"),
    path("admin/homepage/blocks/", homepage.AdminHomepageBlockListCreateView.as_view(), name="admin-homepage-block-list"),
    path("admin/homepage/blocks/reorder/", homepage.AdminHomepageBlockReorderView.as_view(), name="admin-homepage-block-reorder"),
    path("admin/homepage/blocks/<int:pk>/", homepage.AdminHomepageBlockDetailView.as_view(), name="admin-homepage-block-detail"),
    path("admin/categories/", categories.AdminCategoryListCreateView.as_view(), name="admin-category-list"),
    path("admin/categories/<int:pk>/", categories.AdminCategoryDetailView.as_view(), name="admin-category-detail"),
    # Orders
    path("admin/orders/", orders.AdminOrderListView.as_view(), name="admin-order-list"),
    path("admin/orders/<int:pk>/", orders.AdminOrderDetailView.as_view(), name="admin-order-detail"),
    path("admin/orders/<int:pk>/mark-paid/", orders.AdminOrderMarkPaidView.as_view(), name="admin-order-mark-paid"),
    path("admin/orders/<int:pk>/start-processing/", orders.AdminOrderStartProcessingView.as_view(), name="admin-order-start-processing"),
    path("admin/orders/<int:pk>/ready-to-ship/", orders.AdminOrderReadyToShipView.as_view(), name="admin-order-ready-to-ship"),
    path("admin/orders/<int:pk>/mark-shipped/", orders.AdminOrderMarkShippedView.as_view(), name="admin-order-mark-shipped"),
    path("admin/orders/<int:pk>/mark-delivered/", orders.AdminOrderMarkDeliveredView.as_view(), name="admin-order-mark-delivered"),
    path("admin/orders/<int:pk>/transition/", orders.AdminOrderTransitionView.as_view(), name="admin-order-transition"),
    path("admin/orders/<int:pk>/serials/", orders.AdminOrderSerialsView.as_view(), name="admin-order-serials"),
    path("admin/orders/<int:pk>/cancel/", orders.AdminOrderCancelView.as_view(), name="admin-order-cancel"),
    path("admin/orders/<int:pk>/invoice.pdf", orders.AdminOrderInvoicePdfView.as_view(), name="admin-order-invoice-pdf"),
    path("admin/orders/<int:pk>/packing-slip.pdf", orders.AdminOrderPackingSlipPdfView.as_view(), name="admin-order-packing-slip-pdf"),
    path("admin/orders/<int:pk>/shipping-label.pdf", orders.AdminOrderShippingLabelPdfView.as_view(), name="admin-order-shipping-label-pdf"),
    path("admin/orders/<int:pk>/warranty-cards.pdf", orders.AdminOrderWarrantyCardsPdfView.as_view(), name="admin-order-warranty-cards-pdf"),
    path("admin/orders/daily-shipping-list.pdf", orders.AdminDailyShippingListPdfView.as_view(), name="admin-daily-shipping-list-pdf"),
    # Payments / receipts (D-05 §۳)
    path("admin/payments/", payments.AdminPaymentListView.as_view(), name="admin-payment-list"),
    path("admin/payments/receipts/", payments.AdminPaymentReceiptListView.as_view(), name="admin-payment-receipt-list"),
    path("admin/payments/receipts/<int:pk>/", payments.AdminPaymentReceiptReviewView.as_view(), name="admin-payment-receipt-review"),
    path("admin/payments/receipts/<int:pk>/file/", payments.AdminPaymentReceiptFileView.as_view(), name="admin-payment-receipt-file"),
    # Search Console
    # AUDIT-6 — پنل ترب (Torob API v3)
    path("admin/torob/status/", torob_admin.AdminTorobStatusView.as_view(), name="admin-torob-status"),
    path("admin/torob/validate/", torob_admin.AdminTorobValidateView.as_view(), name="admin-torob-validate"),
    path("admin/search-console/status/", search_console.AdminSearchConsoleStatusView.as_view(), name="admin-sc-status"),
    path("admin/search-console/performance/", search_console.AdminSearchConsolePerformanceView.as_view(), name="admin-sc-performance"),
    path("admin/search-console/queries/", search_console.AdminSearchConsoleQueriesView.as_view(), name="admin-sc-queries"),
    path("admin/search-console/pages/", search_console.AdminSearchConsolePagesView.as_view(), name="admin-sc-pages"),
    path("admin/search-console/index-status/", search_console.AdminSearchConsoleIndexStatusView.as_view(), name="admin-sc-index-status"),
    path("admin/search-console/sitemap-status/", search_console.AdminSearchConsoleSitemapStatusView.as_view(), name="admin-sc-sitemap-status"),
    # Users
    path("admin/users/", users.AdminUserListCreateView.as_view(), name="admin-user-list"),
    path("admin/users/<int:pk>/", users.AdminUserDetailView.as_view(), name="admin-user-detail"),
    path("admin/users/<int:user_id>/addresses/", users.AdminUserAddressListView.as_view(), name="admin-user-addresses"),
    path("admin/users/<int:user_id>/statement.pdf", users.AdminCustomerStatementPdfView.as_view(), name="admin-user-statement-pdf"),
    # Password management (§7.6) — all superuser-only
    path("admin/users/<int:user_id>/reset-password/", account_admin.AdminResetPasswordView.as_view(), name="admin-user-reset-password"),
    path("admin/users/<int:user_id>/impersonate/", account_admin.AdminImpersonateView.as_view(), name="admin-user-impersonate"),
    path("admin/users/<int:user_id>/force-logout/", account_admin.AdminForceLogoutView.as_view(), name="admin-user-force-logout"),
    # Messages
    path("admin/redirects/", redirects.AdminRedirectListCreateView.as_view(), name="admin-redirect-list"),
    path("admin/redirects/<int:pk>/", redirects.AdminRedirectDetailView.as_view(), name="admin-redirect-detail"),
    path("admin/pages/about/", content_pages.AdminAboutPageView.as_view(), name="admin-page-about"),
    path("admin/pages/legal/", content_pages.AdminLegalDocumentListView.as_view(), name="admin-page-legal-list"),
    path("admin/pages/legal/<str:key>/", content_pages.AdminLegalDocumentDetailView.as_view(), name="admin-page-legal-detail"),
    path("admin/messages/", contact_messages.AdminMessageListView.as_view(), name="admin-message-list"),
    path("admin/messages/<int:pk>/", contact_messages.AdminMessageDetailView.as_view(), name="admin-message-detail"),
    # Sales reports
    path("admin/reports/sales/", reports.AdminSalesReportView.as_view(), name="admin-report-sales"),
    path("admin/reports/sales/export/", reports.AdminSalesReportExportView.as_view(), name="admin-report-sales-export"),
    path("admin/reports/sales/export.pdf", reports.AdminSalesReportPdfView.as_view(), name="admin-report-sales-pdf"),
    path("admin/reports/top-products/", reports.AdminTopProductsReportView.as_view(), name="admin-report-top-products"),
    path("admin/reports/by-category/", reports.AdminByCategoryReportView.as_view(), name="admin-report-by-category"),
    path("admin/reports/conversion/", reports.AdminConversionReportView.as_view(), name="admin-report-conversion"),
    path("admin/reports/abandoned-carts/", reports.AdminAbandonedCartsReportView.as_view(), name="admin-report-abandoned-carts"),
    path("admin/reports/customers/", reports.AdminCustomersReportView.as_view(), name="admin-report-customers"),
    path("admin/reports/by-gateway/", reports.AdminByGatewayReportView.as_view(), name="admin-report-by-gateway"),
    path("admin/reports/return-rate/", reports.AdminReturnRateReportView.as_view(), name="admin-report-return-rate"),
    path("admin/reports/gross-margin/", reports.AdminGrossMarginReportView.as_view(), name="admin-report-gross-margin"),
    # Settings
    path("admin/settings/site/", settings_admin.AdminSiteSettingsView.as_view(), name="admin-settings-site"),
    path("admin/settings/credentials/", settings_admin.AdminApiCredentialListCreateView.as_view(), name="admin-settings-credential-list"),
    path("admin/settings/credentials/test-sms/", settings_admin.AdminTestSmsView.as_view(), name="admin-settings-test-sms"),
    path("admin/settings/sms-templates/", settings_admin.AdminSmsTemplateListView.as_view(), name="admin-settings-sms-templates"),
    path("admin/settings/sms-templates/<int:pk>/", settings_admin.AdminSmsTemplateDetailView.as_view(), name="admin-settings-sms-template-detail"),
    path("admin/settings/sms-logs/", settings_admin.AdminSmsLogListView.as_view(), name="admin-settings-sms-logs"),
    path("admin/settings/credentials/<int:pk>/", settings_admin.AdminApiCredentialDetailView.as_view(), name="admin-settings-credential-detail"),
    path("admin/settings/shipping-methods/", settings_admin.AdminShippingMethodListCreateView.as_view(), name="admin-settings-shipping-list"),
    path("admin/settings/shipping-methods/<int:pk>/", settings_admin.AdminShippingMethodDetailView.as_view(), name="admin-settings-shipping-detail"),
    # Reviews
    path("admin/reviews/", reviews.AdminReviewListView.as_view(), name="admin-review-list"),
    path("admin/reviews/<int:pk>/", reviews.AdminReviewDetailView.as_view(), name="admin-review-detail"),
    # Blog
    path("admin/blog/", blog.AdminBlogPostListCreateView.as_view(), name="admin-blog-list"),
    path("admin/blog/<int:pk>/", blog.AdminBlogPostDetailView.as_view(), name="admin-blog-detail"),
    # Coupons
    path("admin/coupons/", coupons.AdminCouponListCreateView.as_view(), name="admin-coupon-list"),
    path("admin/coupons/<int:pk>/", coupons.AdminCouponDetailView.as_view(), name="admin-coupon-detail"),
    # Returns
    path("admin/returns/", returns.AdminReturnListView.as_view(), name="admin-return-list"),
    path("admin/returns/<int:pk>/", returns.AdminReturnDetailView.as_view(), name="admin-return-detail"),
    path("admin/returns/<int:pk>/approve/", returns.AdminReturnApproveView.as_view(), name="admin-return-approve"),
    path("admin/returns/<int:pk>/reject/", returns.AdminReturnRejectView.as_view(), name="admin-return-reject"),
    path("admin/returns/<int:pk>/mark-received/", returns.AdminReturnMarkReceivedView.as_view(), name="admin-return-mark-received"),
    path("admin/returns/<int:pk>/mark-refunded/", returns.AdminReturnMarkRefundedView.as_view(), name="admin-return-mark-refunded"),
    # Activity log
    path("admin/login-attempts/", activity_log_views.AdminLoginAttemptListView.as_view(), name="admin-login-attempts"),
    path("admin/activity-log/", activity_log_views.AdminActivityLogListView.as_view(), name="admin-activity-log"),
]
