# Generated by Django 5.2.17 on 2026-09-24 13:05

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=apps.orders.models.generate_order_number, editable=False, max_length=30, unique=True)),
                ('shipping_address', models.JSONField(default=dict, help_text='{title, province, city, line, postalCode, receiverName, receiverPhone}')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال\u200cشده'), ('delivered', 'تحویل\u200cشده'), ('canceled', 'لغوشده'), ('returned', 'مرجوع\u200cشده')], default='pending', max_length=20)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('shipping_cost', models.PositiveIntegerField(default=0)),
                ('tax', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('invoice_pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=200)),
                ('variant_name_snapshot', models.CharField(blank=True, max_length=200, null=True)),
                ('sku_snapshot', models.CharField(max_length=50)),
                ('spec_snapshot', models.JSONField(blank=True, null=True)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('ZARINPAL', 'زرین\u200cپال'), ('IDPAY', 'آیدی\u200cپی'), ('SNAPPPAY', 'اسنپ\u200cپی'), ('DIGIPAY', 'دیجی\u200cپی')], max_length=20)),
                ('gateway_name', models.CharField(blank=True, max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('authority', models.CharField(blank=True, max_length=100)),
                ('ref_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'درخواست\u200cشده'), ('approved', 'تأییدشده'), ('received', 'دریافت\u200cشده'), ('refunded', 'بازپرداخت\u200cشده'), ('rejected', 'ردشده')], default='requested', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
