# Generated by Django 5.2.17 on 2026-09-29 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_coupon_categories_remove_coupon_ends_at_and_more'),
        ('orders', '0003_couponusage_orderstatushistory_paymentreceipt_and_more'),
        ('settings', '0003_seed_dev_shipping_methods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_applications', to='content.coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='settings.shippingmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='economic_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_type',
            field=models.CharField(choices=[('PERSONAL', 'شخصی'), ('CORPORATE', 'حقوقی')], default='PERSONAL', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='national_id',
            field=models.CharField(blank=True, help_text='شناسه ملی شرکت، ۱۱ رقم', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'idempotency_key'), name='unique_order_idempotency_key_per_user'),
        ),
    ]
