# Generated by Django 5.2.17 on 2026-09-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_coupon_cart_shipping_method_order_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
