# Generated by Django 5.2.17 on 2026-09-29 07:34

import django.db.models.deletion
from django.db import migrations, models

import apps.orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_e03_order_admin_notified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_id', models.CharField(default=apps.orders.models._generate_certificate_id, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='orders.orderitem')),
            ],
            options={
                'indexes': [models.Index(fields=['order_item'], name='orders_orde_order_i_7f166a_idx')],
            },
        ),
    ]
