# Generated by Django 5.2.17 on 2026-09-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_shipping_method_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnitem",
            name="decision",
            field=models.CharField(
                choices=[
                    ("PENDING", "در انتظار"),
                    ("APPROVED", "تأیید"),
                    ("REJECTED", "رد"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
