# Generated by Django 5.2.17 on 2026-09-29 22:38

import shutil
from pathlib import Path

from django.conf import settings
from django.db import migrations, models

import apps.orders.models


def move_receipts_to_private(apps, schema_editor):
    """رسیدهای قبلی از MEDIA_ROOT (قابل سرو عمومی) به PRIVATE_MEDIA_ROOT منتقل می‌شوند؛
    نام نسبی فایل همان می‌ماند تا ردیف‌های دیتابیس درست بمانند."""
    PaymentReceipt = apps.get_model("orders", "PaymentReceipt")
    media, private = Path(settings.MEDIA_ROOT), Path(settings.PRIVATE_MEDIA_ROOT)
    for name in PaymentReceipt.objects.values_list("file", flat=True):
        src, dst = media / name, private / name
        if name and src.exists() and not dst.exists():
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(src), str(dst))


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_f04_return_item_decision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentreceipt",
            name="file",
            field=models.FileField(
                storage=apps.orders.models.private_storage,
                upload_to=apps.orders.models._receipt_upload_path,
            ),
        ),
        migrations.RunPython(move_receipts_to_private, migrations.RunPython.noop),
    ]
