# Generated by Django 5.2.17 on 2026-10-05 07:47

import django.db.models.deletion
from django.db import migrations, models

import apps.orders.models


def backfill_payment_plan(apps, schema_editor):
    # سفارش‌های قبلی: پرداخت درگاهی = آنلاین، بقیه = واریز مستقیم (پیش‌فرض ستون).
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(payments__method="GATEWAY").update(payment_plan="ONLINE")


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_g03_private_receipts"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaleUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_id", models.BigIntegerField(unique=True)),
                ("kind", models.CharField(blank=True, max_length=30)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="payment_plan",
            field=models.CharField(
                choices=[
                    ("ONLINE", "پرداخت آنلاین"),
                    ("BANK_TRANSFER", "واریز مستقیم به حساب"),
                    ("COMBINED", "پرداخت ترکیبی"),
                ],
                default="BANK_TRANSFER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="failure_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "در انتظار پرداخت"),
                    ("RECEIPT_UPLOADED", "رسید ارسال شده"),
                    ("UNDER_REVIEW", "در حال بررسی"),
                    ("CONFIRMED", "تأیید شده"),
                    ("PARTIALLY_PAID", "پرداخت بخشی"),
                    ("FAILED", "ناموفق"),
                    ("VOID", "باطل"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "در انتظار پرداخت"),
                    ("RECEIPT_UPLOADED", "رسید ارسال شده"),
                    ("UNDER_REVIEW", "در حال بررسی"),
                    ("CONFIRMED", "تأیید شده"),
                    ("PARTIALLY_PAID", "پرداخت بخشی"),
                    ("FAILED", "ناموفق"),
                    ("VOID", "باطل"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BalePaySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.orders.models._bale_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "invoice_payload",
                    models.CharField(
                        default=apps.orders.models._bale_payload,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("chat_id", models.BigIntegerField(blank=True, null=True)),
                ("amount_rial", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "ساخته شد"),
                            ("INVOICE_SENT", "فاکتور در بله ارسال شد"),
                            ("PRECHECKOUT_OK", "در حال پرداخت"),
                            ("PAID", "پرداخت شد"),
                            ("FAILED", "ناموفق"),
                            ("EXPIRED", "منقضی"),
                            ("NEEDS_REVIEW", "نیازمند بررسی"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "provider_payment_charge_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "telegram_payment_charge_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bale_sessions",
                        to="orders.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="orders_bale_status_c99e87_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_payment_plan, migrations.RunPython.noop),
    ]
