# Generated by Django 5.2.17 on 2026-10-05 13:18

import django.db.models.functions.text
from django.db import migrations, models

_FULFILMENT_STATUSES = ("PAID", "PROCESSING", "READY_TO_SHIP", "SHIPPED", "DELIVERED")


def check_duplicate_serials(apps, schema_editor):
    """داده‌ی تولید: اگر سریال تکراری هست، migration با پیام روشن متوقف
    می‌شود (به‌جای خطای مبهم ساخت index) تا ادمین اول اصلاحش کند."""
    from django.db.models import Count
    from django.db.models.functions import Upper

    Unit = apps.get_model("orders", "OrderItemUnit")
    dupes = (
        Unit.objects.exclude(serial_number__isnull=True)
        .exclude(serial_number="")
        .annotate(s=Upper("serial_number"))
        .values("s")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    if dupes.exists():
        raise RuntimeError(
            f"AUDIT-5: {dupes.count()} سریال تکراری در OrderItemUnit — پیش از migrate در پنل اصلاح شود: "
            + ", ".join(d["s"] for d in dupes[:20])
        )
    # «» خالی = بدون سریال (هم‌معنای null، شرط قید هم همین است).
    Unit.objects.filter(serial_number="").update(serial_number=None)


def backfill_units(apps, schema_editor):
    """سفارش‌های پرداخت‌شده‌ی موجود که هرگز واحد نگرفتند (فقط Django admin می‌ساخت)."""
    import secrets

    Item = apps.get_model("orders", "OrderItem")
    Unit = apps.get_model("orders", "OrderItemUnit")
    alphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"  # همان _generate_certificate_id
    for item in Item.objects.filter(order__status__in=_FULFILMENT_STATUSES):
        for _ in range(max(0, item.quantity - Unit.objects.filter(order_item=item).count())):
            while True:
                cert = "ARB-W-" + "".join(secrets.choice(alphabet) for _ in range(10))
                if not Unit.objects.filter(certificate_id=cert).exists():
                    break
            Unit.objects.create(order_item=item, certificate_id=cert)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_audit2_payments"),
    ]

    operations = [
        migrations.RunPython(check_duplicate_serials, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="orderitemunit",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("serial_number"),
                condition=models.Q(
                    ("serial_number__isnull", False),
                    models.Q(("serial_number", ""), _negated=True),
                ),
                name="orderitemunit_serial_unique_ci",
            ),
        ),
            migrations.RunPython(backfill_units, migrations.RunPython.noop),
    ]
