# Generated by Django 5.2.17 on 2026-10-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TorobFetchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("page", "صفحه\u200cبندی"),
                            ("cursor", "cursor"),
                            ("page_urls", "با آدرس"),
                            ("page_uniques", "با شناسه"),
                            ("invalid", "نامعتبر"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sort", models.CharField(blank=True, max_length=30)),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("invalid_count", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
